#!/usr/bin/env node

const { program } = require('commander');
const init  = require('./src/seeding/initialize');
const start = require('./src/server');

program
  .option('-s, --seed', 'seed the database')
  .option('-g, --graphql', 'start the graphql server')
 
program.parse(process.argv);

if (program.seed) {
	console.log('Seeing the database');
	init()
		.then(() => console.log('database seeded'),
			err => console.log(err));
} else if (program.graphql) {
	console.log('Starting the GraphQL server');
	start();
} else {
	console.log('unknown arguments')
}