#!/usr/bin/env node

const { program } = require('commander');
const seed  = require('./seeding/initialize');
const server = require('./server');

program
  .option('-s, --seed', 'seed the database')
  .option('-g, --graphql', 'start the graphql server')
 
program.parse(process.argv);

if (program.seed) {
	console.log('Seeing the database');
	console.log(seed)
	seed.init();
} else {
	console.log('Starting the GraphQL server');
	server.start();
}